spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes: #THIS IS HOW YOU ROUTE FROM GATEWAY TO SERVICES THAT ARE REIGSTERED IN EUREKA
        - id: this-is-just-an-identifier #this is just a name
          uri: lb://spring-cloud-eureka-consumer-client #this is important - this uses the built in loadbalancer (lb) of eureka - you need to specify the reigstered eureka client
          predicates:
            - Path=/** #here we specify all the valid paths we can redirect to
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true